import {
  DefaultButton,
  DefaultButtonGroup,
  DefaultCard,
  DefaultCheckboxInput,
  DefaultCol,
  DefaultCurrencyInput,
  DefaultDropdownButton,
  DefaultFormGroup,
  DefaultImage,
  DefaultLink,
  DefaultModal,
  DefaultMultiCheckbox,
  DefaultMultiRadio,
  DefaultNotification,
  DefaultNumberInput,
  DefaultPluginSettingsWrapper,
  DefaultRadioInput,
  DefaultRow,
  DefaultSelectInput,
  DefaultTable,
  DefaultTableCol,
  DefaultTableRow,
  DefaultTextInput,
  DefaultToggleInput,
} from '@myparcel/pdk-components';
import {LogLevel, createPdkFrontend} from '@myparcel/pdk-frontend';
import {PsIcon} from './components';

createPdkFrontend({
  // ...defaultBootstrap4Config,
  logLevel: LogLevel.DEBUG,
  transitions: {
    labelCard: 'fade',
    notification: 'fade',
    shipmentRow: 'fade',
  },

  formConfig: {
    formClass: 'form-horizontal',
  },

  components: {
    PdkButton: DefaultButton,
    PdkButtonGroup: DefaultButtonGroup,
    PdkCard: DefaultCard,
    PdkCheckboxInput: DefaultCheckboxInput,
    PdkCol: DefaultCol,
    PdkCurrencyInput: DefaultCurrencyInput,
    PdkDropdownButton: DefaultDropdownButton,
    PdkFormGroup: DefaultFormGroup,
    PdkImage: DefaultImage,
    PdkLink: DefaultLink,
    PdkModal: DefaultModal,
    PdkMultiCheckbox: DefaultMultiCheckbox,
    PdkMultiRadio: DefaultMultiRadio,
    PdkNotification: DefaultNotification,
    PdkNumberInput: DefaultNumberInput,
    PdkPluginSettingsWrapper: DefaultPluginSettingsWrapper,
    PdkRadioInput: DefaultRadioInput,
    PdkRow: DefaultRow,
    PdkSelectInput: DefaultSelectInput,
    PdkTable: DefaultTable,
    PdkTableCol: DefaultTableCol,
    PdkTableRow: DefaultTableRow,
    PdkTextInput: DefaultTextInput,
    PdkToggleInput: DefaultToggleInput,
    // ...bootstrap4Components,
    // PdkSelectInput: PsSelectInput,
    // PdkTextInput: PsTextInput,
    // PdkToggleInput: PsToggleInput,
    //
    // PdkCheckbox: PsCheckbox,
    // PdkFormGroup: PsFormGroup,
    // PdkRadio: PsRadio,
    // PdkToggle: PsToggleInput,
    //
    // PdkButton: PsButton,
    // PdkDropdownButton: PsDropdownButton,
    //
    // PdkPluginSettingsWrapper: PsPluginSettingsWrapper,
    // PdkAlert: PsAlert,
    // PdkCard: PsCard,
    // PdkImage: PsImage,
    // PdkModal: PsModal,
    // PdkTable: PsTable,

    PdkIcon: PsIcon,
  },
});
