<?php

declare(strict_types=1);

namespace MyParcelNL\PrestaShop\Facade;

use MyParcelNL\Pdk\Base\Facade;
use MyParcelNL\Pdk\Facade\Logger;

/**
 * @see \Doctrine\ORM\EntityManager
 * @method static void flush()
 * @method static bool isOpen()
 */
final class EntityManager extends Facade
{
    /**
     * @param $method
     * @param $args
     *
     * @return mixed
     * @throws \DI\DependencyException
     * @throws \DI\NotFoundException
     * @throws \MyParcelNL\Pdk\Base\Exception\InvalidFacadeException
     * @todo remove this
     */
    public static function __callStatic($method, $args)
    {
        Logger::debug(sprintf('Calling EntityManager::%s()', $method));

        return parent::__callStatic($method, $args); // TODO: Change the autogenerated stub
    }

    protected static function getFacadeAccessor(): string
    {
        return 'ps.entityManager';
    }
}
