<?php

declare(strict_types=1);

namespace MyParcelNL\PrestaShop\Pdk\Service;

use MyParcelNL\Pdk\Plugin\Model\PdkCart;
use MyParcelNL\Pdk\Plugin\Service\DeliveryOptionsService;

/**
 * @todo zorg hier dat er maar 1 carrier gereturned wordt
 */
final class PsDeliveryOptionsService extends DeliveryOptionsService
{
    public function createAllCarrierSettings(PdkCart $cart): array
    {
        return parent::createAllCarrierSettings($cart); // TODO: Change the autogenerated stub
    }
}
